from django.urls import path

from .views import (
    AdminLoginView,
    AdminRepresentativeListView,
    AdminUserDetailView,
    AdminUserListCreateView,
    CheckEmailView,
    CheckPhoneView,
    CheckUsernameView,
    ClientLoginView,
    ClientProfileView,
    ForgotPasswordView,
    LoginView,
    LogoutView,
    MeView,
    RefreshTokenView,
    RegisterView,
    RepresentativeLoginView,
    ResendRegistrationOTPView,
    ResetPasswordView,
    VerifyRegistrationOTPView,
)

urlpatterns = [
    path("signup", RegisterView.as_view(), name="signup"),
    path("signup/", RegisterView.as_view(), name="signup-slash"),
    path("verify-email", VerifyRegistrationOTPView.as_view(), name="verify-email"),
    path(
        "verify-email/",
        VerifyRegistrationOTPView.as_view(),
        name="verify-email-slash",
    ),
    path(
        "resend-verification",
        ResendRegistrationOTPView.as_view(),
        name="resend-verification",
    ),
    path(
        "resend-verification/",
        ResendRegistrationOTPView.as_view(),
        name="resend-verification-slash",
    ),
    path("login", LoginView.as_view(), name="login"),
    path("login/", LoginView.as_view(), name="login-slash"),
    path("login/client", ClientLoginView.as_view(), name="client-login"),
    path("login/client/", ClientLoginView.as_view(), name="client-login-slash"),
    path(
        "login/representative",
        RepresentativeLoginView.as_view(),
        name="representative-login",
    ),
    path(
        "login/representative/",
        RepresentativeLoginView.as_view(),
        name="representative-login-slash",
    ),
    path("login/admin", AdminLoginView.as_view(), name="admin-login"),
    path("login/admin/", AdminLoginView.as_view(), name="admin-login-slash"),
    path("refresh", RefreshTokenView.as_view(), name="token-refresh"),
    path("refresh/", RefreshTokenView.as_view(), name="token-refresh-slash"),
    path("logout", LogoutView.as_view(), name="logout"),
    path("logout/", LogoutView.as_view(), name="logout-slash"),
    path("me", MeView.as_view(), name="me"),
    path("me/", MeView.as_view(), name="me-slash"),
    path("client/profile", ClientProfileView.as_view(), name="client-profile"),
    path(
        "client/profile/",
        ClientProfileView.as_view(),
        name="client-profile-slash",
    ),
    path("users", AdminUserListCreateView.as_view(), name="admin-users"),
    path("users/", AdminUserListCreateView.as_view(), name="admin-users-slash"),
    path(
        "representatives/",
        AdminRepresentativeListView.as_view(),
        name="admin-representatives",
    ),
    path(
        "users/<int:user_id>",
        AdminUserDetailView.as_view(),
        name="admin-user-detail",
    ),
    path(
        "users/<int:user_id>/",
        AdminUserDetailView.as_view(),
        name="admin-user-detail-slash",
    ),
    path("check-username", CheckUsernameView.as_view(), name="check-username"),
    path(
        "check-username/",
        CheckUsernameView.as_view(),
        name="check-username-slash",
    ),
    path("check-email", CheckEmailView.as_view(), name="check-email"),
    path("check-email/", CheckEmailView.as_view(), name="check-email-slash"),
    path("check-phone", CheckPhoneView.as_view(), name="check-phone"),
    path("check-phone/", CheckPhoneView.as_view(), name="check-phone-slash"),
    path("forgot-password", ForgotPasswordView.as_view(), name="forgot-password"),
    path(
        "forgot-password/",
        ForgotPasswordView.as_view(),
        name="forgot-password-slash",
    ),
    path("reset-password", ResetPasswordView.as_view(), name="reset-password"),
    path(
        "reset-password/",
        ResetPasswordView.as_view(),
        name="reset-password-slash",
    ),
]
