# Generated by Django 6.0.6 on 2026-07-03 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('markets', '0002_market_service_cities'),
    ]

    operations = [
        migrations.AddField(
            model_name='market',
            name='scope',
            field=models.CharField(choices=[('general', 'General'), ('service_city', 'Service city')], default='service_city', max_length=20),
        ),
    ]
