# Generated by Django 6.0.8 on 2026-10-01 23:03

import config.media_specs
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('markets', '0013_normalize_market_type_sort_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='market',
            name='cover_focus',
            field=models.JSONField(default=config.media_specs.center_focus),
        ),
    ]
