from django.urls import path

from .views import (
    AddressProductListView,
    AdminMarketClassificationDetailView,
    AdminMarketClassificationListCreateView,
    AdminMarketDetailView,
    AdminMarketListCreateView,
    AdminMarketTypeDetailView,
    AdminMarketTypeListCreateView,
    AdminMarketTypeReorderView,
    HomeView,
    LoginDashboardSnapshotView,
    FeaturedMarketClassificationSummaryView,
    MarketClassificationMarketsView,
    MarketClassificationSummaryView,
    MarketLikeListView,
    MarketLikeToggleView,
    MarketStorefrontDetailView,
    MarketUnlikeView,
    NormalMarketClassificationSummaryView,
    PopularMarketClassificationSummaryView,
    ProductDetailView,
    ProductSearchView,
)

urlpatterns = [
    path("", HomeView.as_view(), name="home"),
    path(
        "login-dashboard-snapshot/",
        LoginDashboardSnapshotView.as_view(),
        name="login-dashboard-snapshot",
    ),
    path(
        "market-classifications/",
        AdminMarketClassificationListCreateView.as_view(),
        name="admin-market-classification-list-create",
    ),
    path(
        "market-classifications/<int:classification_id>/",
        AdminMarketClassificationDetailView.as_view(),
        name="admin-market-classification-detail",
    ),
    path(
        "markets/",
        AdminMarketListCreateView.as_view(),
        name="admin-market-list-create",
    ),
    path(
        "market-types/",
        AdminMarketTypeListCreateView.as_view(),
        name="admin-market-type-list-create",
    ),
    path(
        "market-types/reorder/",
        AdminMarketTypeReorderView.as_view(),
        name="admin-market-type-reorder",
    ),
    path(
        "market-types/<int:market_type_id>/",
        AdminMarketTypeDetailView.as_view(),
        name="admin-market-type-detail",
    ),
    path(
        "markets/likes/",
        MarketLikeListView.as_view(),
        name="market-like-list",
    ),
    path(
        "markets/<int:market_id>/like/",
        MarketLikeToggleView.as_view(),
        name="market-like-toggle",
    ),
    path(
        "markets/<int:market_id>/unlike/",
        MarketUnlikeView.as_view(),
        name="market-unlike",
    ),
    path(
        "markets/<int:market_id>/storefront/",
        MarketStorefrontDetailView.as_view(),
        name="market-storefront-detail",
    ),
    path(
        "markets/<int:market_id>/",
        AdminMarketDetailView.as_view(),
        name="admin-market-detail",
    ),
    path("search/", ProductSearchView.as_view(), name="product-search"),
    path("products/", AddressProductListView.as_view(), name="address-product-list"),
    path(
        "products/<int:product_id>/",
        ProductDetailView.as_view(),
        name="product-detail",
    ),
    path(
        "classifications/",
        MarketClassificationSummaryView.as_view(),
        name="market-classification-summary",
    ),
    path(
        "classifications/featured/",
        FeaturedMarketClassificationSummaryView.as_view(),
        name="market-classification-featured",
    ),
    path(
        "classifications/popular/",
        PopularMarketClassificationSummaryView.as_view(),
        name="market-classification-popular",
    ),
    path(
        "classifications/normal/",
        NormalMarketClassificationSummaryView.as_view(),
        name="market-classification-normal",
    ),
    path(
        "classifications/<int:classification_id>/markets/",
        MarketClassificationMarketsView.as_view(),
        name="market-classification-markets",
    ),
]
