# Generated by Django 6.0.6 on 2026-07-23 12:10

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PartnerApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(max_length=180)),
                ('contact_first_name', models.CharField(max_length=100)),
                ('contact_last_name', models.CharField(max_length=100)),
                ('business_type', models.CharField(choices=[('shop', 'Shop'), ('restaurant', 'Restaurant'), ('service_provider', 'Service Provider')], max_length=30)),
                ('branches_count', models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('applicant_role', models.CharField(choices=[('owner_partner', 'Owner / Partner'), ('manager_legal_representative', 'Manager / Legal Representative')], max_length=40)),
                ('has_trade_license', models.BooleanField()),
                ('email', models.EmailField(max_length=254)),
                ('mobile_number', models.CharField(max_length=30)),
                ('landline', models.CharField(blank=True, max_length=30)),
                ('whatsapp_opt_in', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_review', 'In Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('admin_notes', models.TextField(blank=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='partner_applications', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_partner_applications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at', '-id'),
                'indexes': [models.Index(fields=['status', 'created_at'], name='partners_pa_status_575fef_idx'), models.Index(fields=['applicant', 'status'], name='partners_pa_applica_17f29e_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('branches_count__gte', 1), ('branches_count__lte', 5)), name='partners_application_branches_between_1_and_5')],
            },
        ),
    ]
