from django.urls import path

from .views import (
    AdditionClassificationDetailView,
    AdditionClassificationListCreateView,
    CategoryAttributeDetailView,
    CategoryAttributeListCreateView,
    CategoryClassificationDetailView,
    CategoryClassificationListCreateView,
    CategoryOptionDetailView,
    CategoryOptionListCreateView,
    ProductCategoryDetailView,
    ProductCategoryListCreateView,
    ProductDetailView,
    ProductListCreateView,
    ProductAdditionDetailView,
    ProductAdditionListCreateView,
)

urlpatterns = [
    path(
        "addition-classifications/",
        AdditionClassificationListCreateView.as_view(),
        name="addition-classification-list-create",
    ),
    path(
        "addition-classifications/<int:classification_id>/",
        AdditionClassificationDetailView.as_view(),
        name="addition-classification-detail",
    ),
    path(
        "category-classifications/",
        CategoryClassificationListCreateView.as_view(),
        name="category-classification-list-create",
    ),
    path(
        "category-classifications/<int:classification_id>/",
        CategoryClassificationDetailView.as_view(),
        name="category-classification-detail",
    ),
    path(
        "product-categories/",
        ProductCategoryListCreateView.as_view(),
        name="product-category-list-create",
    ),
    path(
        "product-categories/<int:category_id>/",
        ProductCategoryDetailView.as_view(),
        name="product-category-detail",
    ),
    path(
        "category-attributes/",
        CategoryAttributeListCreateView.as_view(),
        name="category-attribute-list-create",
    ),
    path(
        "category-attributes/<int:attribute_id>/",
        CategoryAttributeDetailView.as_view(),
        name="category-attribute-detail",
    ),
    path(
        "category-options/",
        CategoryOptionListCreateView.as_view(),
        name="category-option-list-create",
    ),
    path(
        "category-options/<int:option_id>/",
        CategoryOptionDetailView.as_view(),
        name="category-option-detail",
    ),
    path(
        "products/",
        ProductListCreateView.as_view(),
        name="product-list-create",
    ),
    path(
        "products/<int:product_id>/",
        ProductDetailView.as_view(),
        name="product-detail",
    ),
    path(
        "product-additions/",
        ProductAdditionListCreateView.as_view(),
        name="product-addition-list-create",
    ),
    path(
        "product-additions/<int:addition_id>/",
        ProductAdditionDetailView.as_view(),
        name="product-addition-detail",
    ),
]
