# Generated by Django 6.0.6 on 2026-07-06 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primary_color', models.CharField(default='#155d72', max_length=7)),
                ('subtle_color', models.CharField(default='#e7f2f4', max_length=7)),
                ('accent_color', models.CharField(default='#f0b64f', max_length=7)),
                ('font_family', models.CharField(default='Cairo', max_length=30)),
                ('brand_name', models.CharField(default='يلا ماركت', max_length=120)),
                ('brand_tagline', models.CharField(default='أول أونلاين ماركت في النيل الكبير', max_length=255)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='dashboard/branding/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Dashboard settings',
                'verbose_name_plural': 'Dashboard settings',
            },
        ),
    ]
