# Generated by Django 6.0.8 on 2026-10-01 23:03

import config.media
import config.media_specs
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_app_launch_media'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='applaunchmedia',
            name='delivery_login_focus',
            field=models.JSONField(default=config.media_specs.top_focus),
        ),
        migrations.AddField(
            model_name='applaunchmedia',
            name='market_login_focus',
            field=models.JSONField(default=config.media_specs.top_focus),
        ),
        migrations.AddField(
            model_name='applaunchmedia',
            name='market_login_poster',
            field=models.ImageField(blank=True, null=True, upload_to='app-launch/posters/'),
        ),
        migrations.CreateModel(
            name='MediaJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slot', models.CharField(choices=[('market_login', 'Market login'), ('campaign', 'Campaign')], max_length=24)),
                ('state', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('ready', 'Ready'), ('failed', 'Failed')], db_index=True, default='pending', max_length=12)),
                ('source', models.FileField(blank=True, storage=config.media.RawPrivateMediaStorage(), upload_to='media-jobs/sources/')),
                ('video', models.FileField(blank=True, storage=config.media.RawPublicMediaStorage(), upload_to='media-jobs/videos/')),
                ('poster', models.ImageField(blank=True, upload_to='media-jobs/posters/')),
                ('metadata', models.JSONField(default=dict)),
                ('error', models.CharField(blank=True, max_length=255)),
                ('error_code', models.CharField(blank=True, max_length=32)),
                ('attempt', models.PositiveSmallIntegerField(default=0)),
                ('attempt_token', models.UUIDField(editable=False, null=True)),
                ('cancelled', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(null=True)),
                ('completed_at', models.DateTimeField(null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='applaunchmedia',
            name='market_login_pending_job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.mediajob'),
        ),
    ]
