# Generated by Django 6.0.8 on 2026-10-01 23:06

import config.media
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_applaunchmedia_delivery_login_focus_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediajob',
            name='custom_poster',
            field=models.ImageField(blank=True, storage=config.media.OptimizedPrivateMediaStorage(), upload_to='media-jobs/custom-posters/'),
        ),
        migrations.CreateModel(
            name='MediaCleanup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('storage_id', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=500)),
                ('delete_after', models.DateTimeField(db_index=True)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('storage_id', 'name'), name='unique_media_cleanup')],
            },
        ),
    ]
