# Generated by Django 6.0.6 on 2026-06-29 12:21

import django.db.models.deletion
import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='courierprofile',
            name='delivery_area',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='courier_profiles', to='locations.deliveryarea'),
        ),
        migrations.AddField(
            model_name='courierprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='courier_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='onetimepassword',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='one_time_passwords', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('username'), name='accounts_user_username_ci_unique'),
        ),
        migrations.AddIndex(
            model_name='onetimepassword',
            index=models.Index(fields=['user', 'purpose', 'created_at'], name='accounts_on_user_id_de6e8a_idx'),
        ),
    ]
