# Generated by Django 6.0.6 on 2026-07-03 18:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_courierprofile_service_city'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('locations', '0002_servicecity_delivery_price_address_service_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='market_region_mode',
            field=models.CharField(blank=True, choices=[('general', 'General'), ('service_city', 'Service city')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='market_region_service_city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='market_region_users', to='locations.servicecity'),
        ),
        migrations.AddField(
            model_name='user',
            name='market_region_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('market_region_mode__isnull', True), ('market_region_service_city__isnull', True)), models.Q(('market_region_mode', 'general'), ('market_region_service_city__isnull', True)), models.Q(('market_region_mode', 'service_city'), ('market_region_service_city__isnull', False)), _connector='OR'), name='accounts_user_market_region_valid'),
        ),
    ]
