# Generated by Django 6.0.6 on 2026-06-20 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_accounts_user_username_ci_unique'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='delivery_area',
        ),
    ]
