# Generated by Codex on 2026-07-05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_user_market_region_mode_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="avatar_image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="avatars/",
            ),
        ),
    ]
