# Generated by Django 6.0.6 on 2026-06-25 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_user_avatar_url_user_birth_date_user_gender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar_url',
            field=models.URLField(blank=True, db_column='avatar', null=True),
        ),
    ]
