# Generated by Django 6.0.6 on 2026-07-10 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_user_soft_delete_original_values'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='auth_token_version',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
