# Generated by Django 6.0.6 on 2026-07-17

from django.db import migrations, models


def verify_existing_users(apps, schema_editor):
    User = apps.get_model("accounts", "User")
    # The old schema used is_active for both account lifecycle and email
    # confirmation, so legacy records cannot be classified safely.
    User.objects.all().update(is_verified=True)


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0009_user_auth_token_version"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_verified",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.RunPython(verify_existing_users, migrations.RunPython.noop),
    ]
