# Generated by Django 6.0.6 on 2026-07-17

import accounts.models
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0010_user_is_verified"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user",
            managers=[
                ("objects", accounts.models.VerifiedUserManager()),
            ],
        ),
    ]
