# Generated by Django 6.0.8 on 2026-08-31 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_social_auth'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_username_pending',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(max_length=30, null=True, unique=True),
        ),
    ]
