# Generated by Django 6.0.8 on 2026-10-04 14:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_incomplete_social_profiles'),
        ('locations', '0011_shippingcompany_courier_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courierprofile',
            name='max_active_orders',
            field=models.PositiveSmallIntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='courierprofile',
            name='service_city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='courier_profiles', to='locations.servicecity'),
        ),
    ]
