# Generated by Django 6.0.8 on 2026-10-08 02:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0018_alter_courierprofile_max_active_orders_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="pendingregistration",
            name="profile_username_pending",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="pendingregistration",
            name="phone",
            field=models.CharField(max_length=30, null=True, unique=True),
        ),
    ]
