# Generated by Django 6.0.6 on 2026-06-20 06:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('markets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='offers/')),
                ('type', models.CharField(choices=[('package', 'Package'), ('flash', 'Flash'), ('discount', 'Discount'), ('announcement', 'Announcement'), ('delivery', 'Delivery')], default='package', max_length=30)),
                ('discount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('active_days', models.JSONField(blank=True, default=list)),
                ('use_limits', models.PositiveIntegerField(blank=True, null=True)),
                ('user_limit', models.PositiveIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('expired', 'Expired')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('market', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='markets.market')),
                ('products', models.ManyToManyField(blank=True, related_name='offers', to='catalog.product')),
            ],
        ),
    ]
