# Generated by Django 6.0.6 on 2026-07-03

from django.db import migrations


def delete_legacy_offers(apps, schema_editor):
    Offer = apps.get_model("offers", "Offer")
    OrderOffer = apps.get_model("orders", "OrderOffer")
    offer_ids = list(Offer.objects.values_list("id", flat=True))
    if not offer_ids:
        return

    OrderOffer.objects.filter(offer_id__in=offer_ids).delete()
    Offer.products.through.objects.filter(offer_id__in=offer_ids).delete()
    Offer.objects.filter(id__in=offer_ids).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("offers", "0001_initial"),
        ("orders", "0002_servicecity_review_flow"),
    ]

    operations = [
        migrations.RunPython(delete_legacy_offers, migrations.RunPython.noop),
    ]
