# Generated by Django 6.0.6 on 2026-07-03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("locations", "0002_servicecity_delivery_price_address_service_city"),
        ("markets", "0003_market_scope"),
        ("offers", "0002_cleanup_legacy_offers"),
    ]

    operations = [
        migrations.AddField(
            model_name="offer",
            name="scope",
            field=models.CharField(
                choices=[
                    ("general", "General"),
                    ("service_city", "Service city"),
                ],
                default="service_city",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="offer",
            name="service_city",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="offers",
                to="locations.servicecity",
            ),
        ),
        migrations.AddConstraint(
            model_name="offer",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("scope", "general"), ("service_city__isnull", True)),
                    models.Q(
                        ("scope", "service_city"),
                        ("service_city__isnull", False),
                    ),
                    _connector="OR",
                ),
                name="offers_offer_region_valid",
            ),
        ),
    ]
