# Generated by Django 6.0.6 on 2026-07-27 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0008_offeritem_apply_product_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='archived_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
