# Generated by Django 6.0.8 on 2026-08-25 03:59

import django.db.models.deletion
import config.media
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_product_subcategories'),
        ('locations', '0008_servicecity_archived_at'),
        ('markets', '0013_normalize_market_type_sort_order'),
        ('offers', '0009_offer_archived_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('internal_name', models.CharField(max_length=160)),
                ('is_active', models.BooleanField(db_index=True, default=False)),
                ('priority', models.PositiveIntegerField(db_index=True, default=0)),
                ('start_time', models.DateTimeField(db_index=True)),
                ('end_time', models.DateTimeField(db_index=True)),
                ('show_in_general', models.BooleanField(default=True)),
                ('audience', models.CharField(choices=[('all_clients', 'All clients'), ('new_clients', 'New clients'), ('returning_clients', 'Returning clients')], default='all_clients', max_length=24)),
                ('teaser_text', models.CharField(max_length=160)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('template', models.CharField(choices=[('hero', 'Hero'), ('split', 'Split'), ('media_focus', 'Media focus')], default='hero', max_length=24)),
                ('sheet_size', models.CharField(choices=[('medium', 'Medium'), ('large', 'Large'), ('near_full', 'Near full')], default='large', max_length=24)),
                ('content_alignment', models.CharField(choices=[('start', 'Start'), ('center', 'Center')], default='center', max_length=12)),
                ('teaser_background_color', models.CharField(default='#FF5A00', max_length=7)),
                ('teaser_text_color', models.CharField(default='#FFFFFF', max_length=7)),
                ('sheet_background_color', models.CharField(default='#FFFFFF', max_length=7)),
                ('sheet_text_color', models.CharField(default='#202124', max_length=7)),
                ('button_background_color', models.CharField(default='#FF5A00', max_length=7)),
                ('button_text_color', models.CharField(default='#FFFFFF', max_length=7)),
                ('media_type', models.CharField(choices=[('none', 'None'), ('image', 'Image'), ('video', 'Video')], default='none', max_length=12)),
                ('teaser_image', models.ImageField(blank=True, null=True, upload_to='home-campaigns/teasers/')),
                ('sheet_image', models.ImageField(blank=True, null=True, upload_to='home-campaigns/images/')),
                ('video', models.FileField(blank=True, null=True, storage=config.media.RawPublicMediaStorage(), upload_to='home-campaigns/videos/')),
                ('video_poster', models.ImageField(blank=True, null=True, upload_to='home-campaigns/posters/')),
                ('open_mode', models.CharField(choices=[('tap_only', 'Tap only'), ('once_per_session', 'Once per session'), ('once_per_day', 'Once per day')], default='tap_only', max_length=24)),
                ('dismiss_behavior', models.CharField(choices=[('collapse_only', 'Collapse only'), ('hide_session', 'Hide for session'), ('hide_day', 'Hide for day')], default='collapse_only', max_length=24)),
                ('action_type', models.CharField(choices=[('none', 'None'), ('offer', 'Offer'), ('product', 'Product'), ('market', 'Market'), ('product_category', 'Product category'), ('external_url', 'External URL'), ('copy_text', 'Copy text')], default='none', max_length=24)),
                ('cta_label', models.CharField(blank=True, default='', max_length=80)),
                ('external_url', models.URLField(blank=True, default='')),
                ('copy_text', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('service_city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='home_campaigns', to='locations.servicecity')),
                ('target_market', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='home_campaigns', to='markets.market')),
                ('target_offer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='home_campaigns', to='offers.offer')),
                ('target_product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='home_campaigns', to='catalog.product')),
                ('target_product_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='home_campaigns', to='catalog.productcategory')),
            ],
            options={
                'ordering': ('-priority', '-updated_at', '-id'),
                'constraints': [models.CheckConstraint(condition=models.Q(('end_time__gt', models.F('start_time'))), name='offers_home_campaign_end_after_start')],
            },
        ),
    ]
