# Generated by Django 6.0.8 on 2026-08-25 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0010_homecampaign'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='homecampaign',
            options={'ordering': ('created_at', 'id')},
        ),
        migrations.RemoveField(
            model_name='homecampaign',
            name='audience',
        ),
        migrations.RemoveField(
            model_name='homecampaign',
            name='priority',
        ),
        migrations.AddField(
            model_name='homecampaign',
            name='use_theme_colors',
            field=models.BooleanField(default=True),
        ),
    ]
