# Generated by Django 6.0.8 on 2026-10-01 23:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_applaunchmedia_delivery_login_focus_and_more'),
        ('offers', '0012_homecampaignimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='homecampaign',
            name='pending_video_job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.mediajob'),
        ),
    ]
