# Generated by Django 6.0.8 on 2026-10-05 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0013_homecampaign_pending_video_job'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homecampaign',
            name='sheet_size',
            field=models.CharField(choices=[('medium', 'Medium'), ('large', 'Large'), ('near_full', 'Near full')], default='medium', max_length=24),
        ),
    ]
