# Generated by Django 6.0.8 on 2026-10-05 21:41

import config.media_specs
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0014_homecampaign_medium_layout_default'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='image_focus',
            field=models.JSONField(default=config.media_specs.center_focus),
        ),
    ]
