from django.test import SimpleTestCase
from django.urls import resolve


# This inventory is derived from the network layers in yalla_market,
# yalla_home, and yalla_admin. Keep it on v1 until each consumer is migrated.
CONSUMER_ROUTES = {
    "yalla_market": (
        ("get", "/api/v1/auth/check-username"),
        ("get", "/api/v1/auth/check-email"),
        ("get", "/api/v1/auth/check-phone"),
        ("post", "/api/v1/auth/signup"),
        ("post", "/api/v1/auth/verify-email"),
        ("post", "/api/v1/auth/resend-verification"),
        ("post", "/api/v1/auth/login/client"),
        ("post", "/api/v1/auth/forgot-password"),
        ("post", "/api/v1/auth/reset-password"),
        ("post", "/api/v1/auth/refresh"),
        ("post", "/api/v1/auth/logout"),
        ("get", "/api/v1/auth/me"),
        ("patch", "/api/v1/auth/client/profile/"),
        ("delete", "/api/v1/auth/client/profile/"),
        ("get", "/api/v1/home/"),
        ("get", "/api/v1/home/classifications/"),
        ("get", "/api/v1/home/classifications/1/markets/"),
        ("get", "/api/v1/home/markets/1/storefront/"),
        ("get", "/api/v1/home/products/"),
        ("get", "/api/v1/home/products/1/"),
        ("get", "/api/v1/home/search/"),
        ("get", "/api/v1/offers/"),
        ("get", "/api/v1/market-region/options/"),
        ("get", "/api/v1/market-region/me/"),
        ("patch", "/api/v1/market-region/me/"),
        ("post", "/api/v1/market-region/detect/"),
        ("get", "/api/v1/addresses/"),
        ("get", "/api/v1/addresses/default/"),
        ("post", "/api/v1/addresses/"),
        ("patch", "/api/v1/addresses/1/"),
        ("patch", "/api/v1/addresses/1/default/"),
        ("delete", "/api/v1/addresses/1/"),
        ("post", "/api/v1/orders/preview/"),
        ("post", "/api/v1/orders/create/"),
        ("get", "/api/v1/orders/my/"),
        ("post", "/api/v1/orders/1/delivery-price/accept/"),
        ("get", "/api/v1/catalog/products/likes/"),
        ("post", "/api/v1/catalog/products/1/like/"),
        ("delete", "/api/v1/catalog/products/1/unlike/"),
        ("get", "/api/v1/home/markets/likes/"),
        ("post", "/api/v1/home/markets/1/like/"),
        ("delete", "/api/v1/home/markets/1/unlike/"),
        ("get", "/api/v1/notifications/"),
        ("patch", "/api/v1/notifications/1/read/"),
        ("delete", "/api/v1/notifications/1/"),
        ("post", "/api/v1/notifications/mark-all-read/"),
        ("delete", "/api/v1/notifications/clear-read/"),
        ("get", "/api/v1/notifications/unread-count/"),
        ("post", "/api/v1/notifications/devices/register/"),
        ("delete", "/api/v1/notifications/devices/unregister/"),
        ("post", "/api/v1/partners/applications/"),
        ("get", "/api/v1/locations/delivery-areas/"),
        ("get", "/api/v1/locations/geocoding/autocomplete/"),
        ("get", "/api/v1/locations/geocoding/reverse/"),
    ),
    "yalla_home": (
        ("post", "/api/v1/auth/login/representative/"),
        ("post", "/api/v1/auth/refresh/"),
        ("post", "/api/v1/auth/logout/"),
        ("get", "/api/v1/auth/me/"),
        ("get", "/api/v1/courier/orders/"),
        ("get", "/api/v1/courier/orders/1/"),
        ("patch", "/api/v1/courier/orders/1/status/"),
        ("get", "/api/v1/notifications/"),
        ("patch", "/api/v1/notifications/1/read/"),
        ("delete", "/api/v1/notifications/1/"),
        ("post", "/api/v1/notifications/mark-all-read/"),
        ("get", "/api/v1/notifications/unread-count/"),
        ("post", "/api/v1/notifications/devices/register/"),
    ),
    "yalla_admin": (
        ("get", "/api/v1/home/login-dashboard-snapshot/"),
        ("post", "/api/v1/auth/login/admin/"),
        ("get", "/api/v1/auth/users/"),
        ("post", "/api/v1/auth/users/"),
        ("get", "/api/v1/auth/users/1/"),
        ("patch", "/api/v1/auth/users/1/"),
        ("get", "/api/v1/auth/representatives/"),
        ("get", "/api/v1/catalog/products/"),
        ("post", "/api/v1/catalog/products/"),
        ("get", "/api/v1/catalog/products/1/"),
        ("patch", "/api/v1/catalog/products/1/"),
        ("delete", "/api/v1/catalog/products/1/"),
        ("get", "/api/v1/home/markets/"),
        ("post", "/api/v1/home/markets/"),
        ("patch", "/api/v1/home/markets/1/"),
        ("delete", "/api/v1/home/markets/1/"),
        ("get", "/api/v1/offers/"),
        ("post", "/api/v1/offers/"),
        ("patch", "/api/v1/offers/1/"),
        ("delete", "/api/v1/offers/1/"),
        ("get", "/api/v1/orders/"),
        ("post", "/api/v1/orders/"),
        ("get", "/api/v1/orders/1/"),
        ("patch", "/api/v1/orders/1/status/"),
        ("patch", "/api/v1/orders/1/delivery-price/"),
        ("patch", "/api/v1/orders/1/assignment/"),
        ("get", "/api/v1/admin/order-review/blocker/"),
        ("post", "/api/v1/admin/orders/1/approve/"),
        ("post", "/api/v1/admin/orders/1/reject/"),
        ("get", "/api/v1/dashboard/overview/"),
        ("get", "/api/v1/dashboard/settings/"),
        ("patch", "/api/v1/dashboard/settings/"),
        ("get", "/api/v1/locations/service-cities/"),
        ("get", "/api/v1/locations/delivery-areas/"),
        ("get", "/api/v1/partners/admin/applications/"),
        ("patch", "/api/v1/partners/admin/applications/1/"),
    ),
}


class ConsumerRouteContractTests(SimpleTestCase):
    def test_every_consumer_route_still_resolves_to_the_expected_method(self):
        checked = 0
        for consumer, routes in CONSUMER_ROUTES.items():
            for method, path in routes:
                with self.subTest(consumer=consumer, method=method, path=path):
                    match = resolve(path)
                    view_class = getattr(match.func, "view_class", None)
                    self.assertIsNotNone(view_class)
                    self.assertTrue(
                        hasattr(view_class, method),
                        f"{consumer} expects {method.upper()} {path}",
                    )
                    checked += 1
        self.assertGreaterEqual(checked, 100)
