# Generated by Django 6.0.6 on 2026-07-04 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0003_delivery_area_pricing_flow'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='manual_area',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='address',
            name='manual_city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
