# Generated by Django 6.0.6 on 2026-07-04 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0004_address_manual_area_address_manual_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
