# Generated by Django 6.0.6 on 2026-07-27 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0006_location_polygons_and_structured_addresses'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryarea',
            name='archived_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
