# Generated by Django 6.0.6 on 2026-07-04 02:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0004_address_manual_area_address_manual_city'),
        ('orders', '0003_order_delivery_area_pricing_flow'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='service_city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='locations.servicecity'),
        ),
    ]
