# Generated by Django 6.0.6 on 2026-07-12 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0006_offer_push_notification_fields'),
        ('orders', '0008_order_authoritative_lifecycle'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='orderoffer',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='orderoffer',
            constraint=models.UniqueConstraint(condition=models.Q(('section__isnull', False)), fields=('order', 'offer', 'section'), name='unique_order_offer_per_section'),
        ),
        migrations.AddConstraint(
            model_name='orderoffer',
            constraint=models.UniqueConstraint(condition=models.Q(('section__isnull', True)), fields=('order', 'offer'), name='unique_order_offer_without_section'),
        ),
    ]
