# Generated by Django 6.0.6 on 2026-07-23 18:10

from django.conf import settings
from django.db import migrations, models


def classify_existing_orders(apps, schema_editor):
    Order = apps.get_model("orders", "Order")
    for order in Order.objects.select_related("delivery_area").iterator():
        if order.delivery_area_id:
            order.fulfillment_type = "direct"
            order.external_shipping_status = "not_required"
            order.eta_min_minutes = order.delivery_area.eta_min_minutes
            order.eta_max_minutes = order.delivery_area.eta_max_minutes
        else:
            order.fulfillment_type = "external_shipping"
            order.external_shipping_status = (
                "quoted" if order.delivery_price is not None else "pending_quote"
            )
        order.save(
            update_fields=[
                "fulfillment_type",
                "external_shipping_status",
                "eta_min_minutes",
                "eta_max_minutes",
            ]
        )


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0006_location_polygons_and_structured_addresses'),
        ('markets', '0008_market_is_popular'),
        ('offers', '0008_offeritem_apply_product_discount'),
        ('orders', '0009_alter_orderoffer_unique_together_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='order',
            name='orders_order_scope_service_city_valid',
        ),
        migrations.AddField(
            model_name='order',
            name='eta_max_minutes',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='eta_min_minutes',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='external_shipping_status',
            field=models.CharField(choices=[('not_required', 'Not required'), ('pending_quote', 'Pending quote'), ('quoted', 'Quoted')], db_index=True, default='pending_quote', max_length=24),
        ),
        migrations.AddField(
            model_name='order',
            name='fulfillment_type',
            field=models.CharField(choices=[('direct', 'Direct delivery'), ('external_shipping', 'External shipping')], db_index=True, default='external_shipping', max_length=24),
        ),
        migrations.RunPython(
            classify_existing_orders,
            migrations.RunPython.noop,
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.CheckConstraint(condition=models.Q(('order_scope__isnull', True), ('order_scope', 'general'), models.Q(('order_scope', 'service_city'), ('service_city__isnull', False)), _connector='OR'), name='orders_order_scope_service_city_valid'),
        ),
    ]
