# Generated by Django 6.0.6 on 2026-07-30 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_remove_order_orders_order_scope_service_city_valid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='external_shipping_status',
            field=models.CharField(choices=[('not_required', 'Not required'), ('pending_quote', 'Pending quote'), ('awaiting_customer_approval', 'Awaiting customer approval'), ('quoted', 'Quoted')], db_index=True, default='pending_quote', max_length=32),
        ),
        migrations.AlterField(
            model_name='orderevent',
            name='event_type',
            field=models.CharField(choices=[('order_created', 'Order created'), ('review_approved', 'Review approved'), ('review_rejected', 'Review rejected'), ('status_changed', 'Status changed'), ('assigned', 'Assigned'), ('unassigned', 'Unassigned'), ('delivery_price_changed', 'Delivery price changed'), ('delivery_quote_sent', 'Delivery quote sent'), ('delivery_quote_accepted', 'Delivery quote accepted'), ('cancelled', 'Cancelled')], max_length=40),
        ),
    ]
