# Generated by Django 6.0.8 on 2026-08-21 08:55

import config.media
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0011_alter_order_external_shipping_status_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="delivery_proof",
            field=models.ImageField(
                blank=True,
                null=True,
                storage=config.media.OptimizedPrivateMediaStorage(),
                upload_to="delivery-proofs/",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                storage=config.media.OptimizedPrivateMediaStorage(),
                upload_to="orders/",
            ),
        ),
    ]
