# Generated by Django 6.0.8 on 2026-09-15 20:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0009_shippingcompany'),
        ('markets', '0013_normalize_market_type_sort_order'),
        ('offers', '0011_alter_homecampaign_options_and_more'),
        ('orders', '0014_order_multi_market_fee'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['status', '-created_at', '-id'], name='orders_orde_status_181fa1_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['review_status', '-created_at', '-id'], name='orders_orde_review__a99158_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['user', '-created_at', '-id'], name='orders_orde_user_id_81d00f_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['assigned_representative', 'status', '-created_at', '-id'], name='orders_orde_assigne_88cfdd_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['-created_at', '-id'], name='orders_orde_created_f2fe3a_idx'),
        ),
    ]
