# Generated by Django 6.0.8 on 2026-10-02 14:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0010_restore_archived_records'),
        ('markets', '0014_market_cover_focus'),
        ('offers', '0013_homecampaign_pending_video_job'),
        ('orders', '0015_add_order_indexes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='client_request_hash',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='order',
            name='client_request_key',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.UniqueConstraint(fields=('user', 'client_request_key'), name='orders_user_request_key_unique'),
        ),
    ]
