# Generated by Django 6.0.8 on 2026-10-02 17:23

from django.db import migrations, models


def backfill_delivery_addresses(apps, schema_editor):
    Order = apps.get_model("orders", "Order")
    fields = ("id", "name", "label", "details", "formatted_address", "address_type",
              "recipient_name", "recipient_phone", "street", "building_name",
              "apartment_number", "floor", "company_name", "additional_instructions",
              "governorate", "district", "manual_city", "manual_area", "delivery_type",
              "fulfillment_type")
    queryset = Order.objects.using(schema_editor.connection.alias).exclude(
        delivery_address_id=None,
    ).select_related("delivery_address__service_city", "delivery_address__delivery_area")
    for order in queryset.iterator(chunk_size=500):
        address = order.delivery_address
        snapshot = {field: getattr(address, field) for field in fields}
        snapshot.update(
            latitude=float(address.latitude) if address.latitude is not None else None,
            longitude=float(address.longitude) if address.longitude is not None else None,
        )
        for relation in ("service_city", "delivery_area"):
            related = getattr(address, relation)
            snapshot[relation] = None if related is None else {
                "id": related.id, "name": related.name,
                "delivery_price": f"{related.delivery_price:.2f}", "is_active": related.is_active,
                **({"service_city_id": related.service_city_id} if relation == "delivery_area" else {}),
            }
        snapshot["delivery_price_preview"] = (
            f"{address.delivery_area.delivery_price:.2f}"
            if address.delivery_type == "fixed_area" and address.delivery_area_id else None
        )
        Order.objects.using(schema_editor.connection.alias).filter(pk=order.pk).update(
            delivery_address_snapshot=snapshot,
        )


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0016_order_client_request_hash_order_client_request_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_address_snapshot',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='additions',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.RunPython(backfill_delivery_addresses, migrations.RunPython.noop),
    ]
