# Generated by Django 6.0.6 on 2026-07-10 13:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
        ('offers', '0004_offer_multi_target_visibility'),
        ('orders', '0008_order_authoritative_lifecycle'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=512, unique=True)),
                ('platform', models.CharField(choices=[('android', 'Android'), ('ios', 'iOS')], max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('last_seen_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='notification',
            name='data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='notification',
            name='offer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='offers.offer'),
        ),
        migrations.AddField(
            model_name='notification',
            name='order_event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='orders.orderevent'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('new_order_review', 'New Order Review'), ('order_assigned', 'Order Assigned'), ('order_rejected', 'Order Rejected'), ('offer_created', 'Offer Created'), ('order_created', 'Order Created'), ('order_review_approved', 'Order Review Approved'), ('order_status_changed', 'Order Status Changed'), ('order_cancelled', 'Order Cancelled'), ('order_failed_delivery', 'Order Failed Delivery')], max_length=50),
        ),
        migrations.AddConstraint(
            model_name='notification',
            constraint=models.UniqueConstraint(condition=models.Q(('offer__isnull', False), ('type', 'offer_created')), fields=('recipient', 'offer'), name='notifications_offer_recipient_unique'),
        ),
        migrations.AddConstraint(
            model_name='notification',
            constraint=models.UniqueConstraint(condition=models.Q(('order_event__isnull', False)), fields=('recipient', 'order_event'), name='notifications_order_event_recipient_unique'),
        ),
        migrations.AddField(
            model_name='clientdevice',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_devices', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='clientdevice',
            index=models.Index(fields=['user', 'is_active'], name='notificatio_user_id_82ac58_idx'),
        ),
    ]
