# Generated by Django 6.0.6 on 2026-07-10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0002_clientdevice_notification_data_notification_offer_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="type",
            field=models.CharField(
                choices=[
                    ("new_order_review", "New Order Review"),
                    ("order_assigned", "Order Assigned"),
                    ("order_rejected", "Order Rejected"),
                    ("offer_created", "Offer Created"),
                    ("order_created", "Order Created"),
                    ("order_review_approved", "Order Review Approved"),
                    ("order_status_changed", "Order Status Changed"),
                    ("order_cancelled", "Order Cancelled"),
                    ("order_failed_delivery", "Order Failed Delivery"),
                    ("account_disabled", "Account Disabled"),
                ],
                max_length=50,
            ),
        ),
    ]
