# Generated by Django 6.0.6 on 2026-07-13

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0004_productimage"),
        ("notifications", "0007_offernotificationdispatch_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductNotificationDispatch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("request_id", models.UUIDField(default=uuid.uuid4, unique=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("recipient_count", models.PositiveIntegerField(default=0)),
                ("notification_count", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("error_message", models.TextField(blank=True)),
                (
                    "product",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="notification_dispatches",
                        to="catalog.product",
                    ),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="product_notification_dispatches",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="notification",
            name="type",
            field=models.CharField(
                choices=[
                    ("new_order_review", "New Order Review"),
                    ("order_assigned", "Order Assigned"),
                    ("order_unassigned", "Order Unassigned"),
                    ("order_rejected", "Order Rejected"),
                    ("offer_created", "Offer Created"),
                    ("product_created", "Product Created"),
                    ("order_created", "Order Created"),
                    ("order_review_approved", "Order Review Approved"),
                    ("order_status_changed", "Order Status Changed"),
                    ("order_cancelled", "Order Cancelled"),
                    ("order_failed_delivery", "Order Failed Delivery"),
                    ("account_disabled", "Account Disabled"),
                    ("account_restored", "Account Restored"),
                    (
                        "courier_availability_changed",
                        "Courier Availability Changed",
                    ),
                    ("courier_profile_updated", "Courier Profile Updated"),
                    ("password_changed", "Password Changed"),
                ],
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="notification",
            name="product",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="notifications",
                to="catalog.product",
            ),
        ),
        migrations.AddField(
            model_name="notification",
            name="product_dispatch",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="notifications",
                to="notifications.productnotificationdispatch",
            ),
        ),
        migrations.AddConstraint(
            model_name="notification",
            constraint=models.UniqueConstraint(
                condition=models.Q(("product_dispatch__isnull", False)),
                fields=("product_dispatch", "recipient"),
                name="notifications_product_dispatch_recipient_unique",
            ),
        ),
    ]
