# Generated by Django 6.0.6 on 2026-07-13 15:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_productimage'),
        ('markets', '0008_market_is_popular'),
        ('notifications', '0009_merge_product_and_delivery_area_notifications'),
        ('offers', '0006_offer_push_notification_fields'),
        ('orders', '0009_alter_orderoffer_unique_together_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('new_order_review', 'New Order Review'), ('order_assigned', 'Order Assigned'), ('order_unassigned', 'Order Unassigned'), ('order_rejected', 'Order Rejected'), ('offer_created', 'Offer Created'), ('product_created', 'Product Created'), ('order_created', 'Order Created'), ('order_review_approved', 'Order Review Approved'), ('order_status_changed', 'Order Status Changed'), ('order_cancelled', 'Order Cancelled'), ('order_failed_delivery', 'Order Failed Delivery'), ('account_disabled', 'Account Disabled'), ('account_restored', 'Account Restored'), ('delivery_area_created', 'Delivery Area Created'), ('market_created', 'Market Created'), ('courier_availability_changed', 'Courier Availability Changed'), ('courier_profile_updated', 'Courier Profile Updated'), ('password_changed', 'Password Changed')], max_length=50),
        ),
        migrations.CreateModel(
            name='MarketNotificationDispatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('recipient_count', models.PositiveIntegerField(default=0)),
                ('notification_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('market', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notification_dispatch', to='markets.market')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='market_notification_dispatches', to=settings.AUTH_USER_MODEL)),
                ('trigger_product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='market_notification_dispatches', to='catalog.product')),
            ],
        ),
        migrations.AddField(
            model_name='notification',
            name='market_dispatch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='notifications', to='notifications.marketnotificationdispatch'),
        ),
        migrations.AddConstraint(
            model_name='notification',
            constraint=models.UniqueConstraint(condition=models.Q(('market_dispatch__isnull', False)), fields=('market_dispatch', 'recipient'), name='notifications_market_dispatch_recipient_unique'),
        ),
    ]
